"use strict";
use(function () {
var calculators = {
    "DP":{
       "dates":{
          "draft_available":"2018-12-01",
          "draft_effective":"2019-01-01"
       },
       "draft":{
          "fees":{
             "additions_manufactured_home_10m2_or_less":{
                "base_fee":192,
                "grades_fee":0,
                "DCP_fee":0,
                "advertising_fee":0
             },
             "additions_manufactured_home_over_10m2":{
                "base_fee":311,
                "grades_fee":0,
                "DCP_fee":163,
                "advertising_fee":0
             },
             "additions_single_semi-detached_duplex_10m2_or_less":{
                "base_fee":384,
                "grades_fee":0,
                "DCP_fee":0,
                "advertising_fee":32
             },
             "additions_single_semi-detached_duplex_over_10m2":{
                "base_fee":621,
                "grades_fee":472,
                "DCP_fee":163,
                "advertising_fee":32
             },
             "new_secondary_suite":{
                "base_fee":0,
                "grades_fee":0,
                "DCP_fee":0,
                "advertising_fee":0
             },
             "new_contextual_dwellings_in_developed_area":{
                "base_fee":393,
                "grades_fee":472,
                "DCP_fee":245,
                "advertising_fee":0
             },
             "development_design_guidelines":{
                "base_fee":621,
                "grades_fee":0,
                "DCP_fee":0,
                "advertising_fee":32
             },
             "new_home_occupation_class_2":{
                "base_fee":449,
                "grades_fee":0,
                "DCP_fee":0,
                "advertising_fee":32
             },
             "new_manufactured_home":{
                "base_fee":592,
                "grades_fee":0,
                "DCP_fee":245,
                "advertising_fee":0
             },
             "new_multi-residential_development_discretionary_use_or_relaxations_required":{
                "base_fee":837,
                "base_fee_per_unit":50,
                "grades_fee":0,
                "DCP_fee":245,
                "advertising_fee":32
             },
             "new_multi-residential_development_permitted_use":{
                "base_fee":837,
                "base_fee_per_unit":50,
                "grades_fee":0,
                "DCP_fee":245,
                "advertising_fee":0
             },
             "new_single_detached_semi-detached_duplex_in_developed_area":{
                "base_fee":1183,
                "grades_fee":472,
                "DCP_fee":245,
                "advertising_fee":32
             },
             "relaxations_proposed_structures":{
                "base_fee":384,
                "grades_fee":0,
                "DCP_fee":163,
                "advertising_fee":32
             },
             "relaxations_existing_structures":{
                "base_fee":167,
                "grades_fee":0,
                "DCP_fee":0,
                "advertising_fee":32
             },
             "renovations_permitted_use":{
                "base_fee":690,
                "grades_fee":0,
                "DCP_fee":163,
                "advertising_fee":0
             },
             "renovations_discretionary_use":{
                "base_fee":690,
                "grades_fee":0,
                "DCP_fee":163,
                "advertising_fee":32
             },
             "additions_commercial_buildings":{
                "base_fee_per_metre":{
                   "fee":0.8,
                   "min":1823
                },
                "DCP_fee":245,
                "advertising_fee":32
             },
             "additions_mixed_use_buildings":{
                "base_fee":837,
                "base_fee_per_unit":50,
                "base_fee_per_metre":{
                   "fee":0.8,
                   "min":1823
                },
                "DCP_fee":245,
                "advertising_fee":32
             },
             "change_of_use_permitted_use":{
                "base_fee":200,
                "DCP_fee":0,
                "advertising_fee":0
             },
             "change_of_use_discretionary_use":{
                "base_fee":625,
                "DCP_fee":0,
                "advertising_fee":32
             },
             "general_excavating_stripping_and_grading":{
                "base_fee":1173,
                "DCP_fee":0,
                "advertising_fee":32
             },
             "general_outdoor_cafes":{
                "base_fee":621,
                "DCP_fee":245,
                "advertising_fee":32
             },
             "general_retaining_walls":{
                "base_fee":980,
                "DCP_fee":163,
                "advertising_fee":32
             },
             "general_special_function":{
                "base_fee":380,
                "DCP_fee":245,
                "advertising_fee":32
             },
             "general_surface_parking_lots":{
                "base_fee":1173,
                "DCP_fee":245,
                "advertising_fee":32
             },
             "general_temporary_structures":{
                "base_fee":980,
                "DCP_fee":0,
                "advertising_fee":32
             },
             "renovations_changes_to_site_plan":{
                "base_fee":1634,
                "DCP_fee":163,
                "advertising_fee":32
             },
             "renovations_exterior_renovations":{
                "base_fee":621,
                "DCP_fee":163,
                "advertising_fee":32
             },
             "renovations_mezzanine_permitted_use":{
                "base_fee":621,
                "DCP_fee":163,
                "advertising_fee":0
             },
             "renovations_mezzanine_discretionary_use":{
                "base_fee":621,
                "DCP_fee":163,
                "advertising_fee":32
             },
             "signs_permitted_use":{
                "base_fee":100,
                "DCP_fee":0,
                "advertising_fee":0
             },
             "signs_discretionary_use":{
                "base_fee":669,
                "DCP_fee":163,
                "advertising_fee":32
             },
             "CPC_fee":{
                "base_fee":653,
                "DCP_fee":0,
                "advertising_fee":0
             },
             "planning_approval_for_business_licence_applications":{
                "base_fee":41,
                "DCP_fee":0,
                "advertising_fee":0
             },
             "recirculation_fee":{
                "base_fee":1203,
                "DCP_fee":0,
                "advertising_fee":0
             },
             "antennas_type_A":{
                "base_fee":3266
             },
             "antennas_type_B":{
                "base_fee":817
             },
             "antennas_type_C":{
                "base_fee":124
             },
             "antennas_amateur_radio_towers":{
                "base_fee":311
             },
             "certificate_of_compliance_residential":{
                "base_fee":199
             },
             "certificate_of_compliance_other_14_day":{
                "base_fee":296
             },
             "certificate_of_compliance_other_7_day":{
                "base_fee":455
             },
             "condominium_application":{
                "base_fee":40
             },
             "confirmation_of_land_use":{
                "base_fee":77
             },
             "CPAG_pre_application":{
                "base_fee":1000
             },
             "development_agreement_status_letter":{
                "base_fee":491
             },
             "home_occupation_class_1":{
                "base_fee":0
             },
             "commercial_use_of_public_easement_space":{
                "base_fee":11.09
             },
             "pushcarts_non-food":{
                "base_fee":547
             },
             "pushcarts_food":{
                "base_fee":817
             }
          }
       },
       "live":{
          "fees":{
             "additions_manufactured_home_10m2_or_less":{
                "base_fee":192,
                "grades_fee":0,
                "DCP_fee":0,
                "advertising_fee":0
             },
             "additions_manufactured_home_over_10m2":{
                "base_fee":311,
                "grades_fee":0,
                "DCP_fee":163,
                "advertising_fee":0
             },
             "additions_single_semi-detached_duplex_10m2_or_less":{
                "base_fee":384,
                "grades_fee":0,
                "DCP_fee":0,
                "advertising_fee":32
             },
             "additions_single_semi-detached_duplex_over_10m2":{
                "base_fee":621,
                "grades_fee":472,
                "DCP_fee":163,
                "advertising_fee":32
             },
             "new_secondary_suite":{
                "base_fee":0,
                "grades_fee":0,
                "DCP_fee":0,
                "advertising_fee":0
             },
             "new_contextual_dwellings_in_developed_area":{
                "base_fee":393,
                "grades_fee":472,
                "DCP_fee":245,
                "advertising_fee":0
             },
             "development_design_guidelines":{
                "base_fee":621,
                "grades_fee":0,
                "DCP_fee":0,
                "advertising_fee":32
             },
             "new_home_occupation_class_2":{
                "base_fee":449,
                "grades_fee":0,
                "DCP_fee":0,
                "advertising_fee":32
             },
             "new_manufactured_home":{
                "base_fee":592,
                "grades_fee":0,
                "DCP_fee":245,
                "advertising_fee":0
             },
             "new_multi-residential_development_discretionary_use_or_relaxations_required":{
                "base_fee":837,
                "base_fee_per_unit":50,
                "grades_fee":0,
                "DCP_fee":245,
                "advertising_fee":32
             },
             "new_multi-residential_development_permitted_use":{
                "base_fee":837,
                "base_fee_per_unit":50,
                "grades_fee":0,
                "DCP_fee":245,
                "advertising_fee":0
             },
             "new_single_detached_semi-detached_duplex_in_developed_area":{
                "base_fee":1183,
                "grades_fee":472,
                "DCP_fee":245,
                "advertising_fee":32
             },
             "relaxations_proposed_structures":{
                "base_fee":380,
                "grades_fee":0,
                "DCP_fee":163,
                "advertising_fee":32
             },
             "relaxations_existing_structures":{
                "base_fee":380,
                "grades_fee":0,
                "DCP_fee":0,
                "advertising_fee":32
             },
             "renovations_permitted_use":{
                "base_fee":690,
                "grades_fee":0,
                "DCP_fee":163,
                "advertising_fee":0
             },
             "renovations_discretionary_use":{
                "base_fee":690,
                "grades_fee":0,
                "DCP_fee":163,
                "advertising_fee":32
             },
             "additions_commercial_buildings":{
                "base_fee_per_metre":{
                   "fee":0.8,
                   "min":1823
                },
                "DCP_fee":245,
                "advertising_fee":32
             },
             "additions_mixed_use_buildings":{
                "base_fee":837,
                "base_fee_per_unit":50,
                "base_fee_per_metre":{
                   "fee":0.8,
                   "min":1823
                },
                "DCP_fee":245,
                "advertising_fee":32
             },
             "change_of_use_permitted_use":{
                "base_fee":196,
                "DCP_fee":0,
                "advertising_fee":0
             },
             "change_of_use_discretionary_use":{
                "base_fee":621,
                "DCP_fee":0,
                "advertising_fee":32
             },
             "general_excavating_stripping_and_grading":{
                "base_fee":1173,
                "DCP_fee":0,
                "advertising_fee":32
             },
             "general_outdoor_cafes":{
                "base_fee":621,
                "DCP_fee":245,
                "advertising_fee":32
             },
             "general_retaining_walls":{
                "base_fee":980,
                "DCP_fee":163,
                "advertising_fee":32
             },
             "general_special_function":{
                "base_fee":380,
                "DCP_fee":245,
                "advertising_fee":32
             },
             "general_surface_parking_lots":{
                "base_fee":1173,
                "DCP_fee":245,
                "advertising_fee":32
             },
             "general_temporary_structures":{
                "base_fee":980,
                "DCP_fee":0,
                "advertising_fee":32
             },
             "renovations_changes_to_site_plan":{
                "base_fee":1634,
                "DCP_fee":163,
                "advertising_fee":32
             },
             "renovations_exterior_renovations":{
                "base_fee":621,
                "DCP_fee":163,
                "advertising_fee":32
             },
             "renovations_mezzanine_permitted_use":{
                "base_fee":621,
                "DCP_fee":163,
                "advertising_fee":0
             },
             "renovations_mezzanine_discretionary_use":{
                "base_fee":621,
                "DCP_fee":163,
                "advertising_fee":32
             },
             "signs_permitted_use":{
                "base_fee":100,
                "DCP_fee":0,
                "advertising_fee":0
             },
             "signs_discretionary_use":{
                "base_fee":669,
                "DCP_fee":163,
                "advertising_fee":32
             },
             "CPC_fee":{
                "base_fee":653,
                "DCP_fee":0,
                "advertising_fee":0
             },
             "planning_approval_for_business_licence_applications":{
                "base_fee":41,
                "DCP_fee":0,
                "advertising_fee":0
             },
             "recirculation_fee":{
                "base_fee":1203,
                "DCP_fee":0,
                "advertising_fee":0
             },
             "antennas_type_A":{
                "base_fee":3266
             },
             "antennas_type_B":{
                "base_fee":817
             },
             "antennas_type_C":{
                "base_fee":124
             },
             "antennas_amateur_radio_towers":{
                "base_fee":311
             },
             "certificate_of_compliance_residential":{
                "base_fee":169
             },
             "certificate_of_compliance_other_14_day":{
                "base_fee":296
             },
             "certificate_of_compliance_other_7_day":{
                "base_fee":455
             },
             "condominium_application":{
                "base_fee":40
             },
             "confirmation_of_land_use":{
                "base_fee":77
             },
             "CPAG_pre_application":{
                "base_fee":631
             },
             "development_agreement_status_letter":{
                "base_fee":491
             },
             "home_occupation_class_1":{
                "base_fee":0
             },
             "commercial_use_of_public_easement_space":{
                "base_fee":11.09
             },
             "pushcarts_non-food":{
                "base_fee":547
             },
             "pushcarts_food":{
                "base_fee":817
             }
          }
       }
    }
 }
 return calculators;
});